export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POSTS = 'ADD_POSTS';
export const ERROR_DOWNLOAD_POSTS = 'ERROR_DOWNLOAD_POSTS';
export const WAIT_POSTS = 'WAIT_POSTS';
export const REQUESTS_POSTS = 'REQUESTS_POSTS';

// comments
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ERROR_COMMENTS = 'ERROR_COMMENTS';
export const WAIT_COMMENTS = 'WAIT_COMMENTS';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';

// modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const MOVE_MODAL = 'MOVE_MODAL';

// form 
export const VALID_FORM_SUCCESS = 'VALID_FORM_SUCCESS';
export const VALID_FORM_UNSUCCESS = 'VALID_FORM_UNSUCCESS';
export const SAVE_FORM = 'SAVE_FORM';
export const REQUEST_VALID_FORM = 'REQUEST_VALID_FORM';

// dispatch
export const DiSPATCH_FORM_DATA = 'DiSPATCH_FORM_DATA';
export const START_DiSPATCH_FORM_DATA = 'START_DiSPATCH_FORM_DATA';
export const WAITING_DiSPATCH_FORM_DATA = 'WAITING_DiSPATCH_FORM_DATA';
export const SUCCESS_DiSPATCH_FORM_DATA = 'SUCCESS_DiSPATCH_FORM_DATA';
export const ERROR_DiSPATCH_FORM_DATA = 'ERROR_DiSPATCH_FORM_DATA';